config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :contacts
  get '/livingroom' => 'pages#livingroom'
  get '/electronics' => 'pages#electronics'
  get '/beds' => 'pages#beds'
  get '/appliances' => 'pages#appliances'
  get '/call' => 'pages#call'
  get '/apply' => 'pages#apply'
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true
    validates :Current_Address, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :zip, presence: true
    
    
end

app/models/plan.rb
class Plan < ActiveRecord::Base

has_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def new
        @contact = Contact.new
    end
    
    def create
        @contact= Contact.new(contact_params)
        
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
        
            
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = 'Message Sent.'
            redirect_to new_contact_path
        else
            flash[:error] = 'Error Occured, message has not been sent.'
            redirect_to new_contact_path
        end
    
    end
    
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :Current_Address, :city, :state, :zip, :how_long?, :dependents, :home_phone_number, :Cell_number, :rent_payment, :Landlord, :phone_number, :name_on_lease?, :employer, :occupation, :how_long_at_work?, :supervisor, :phone_number, :monthly_income)
        end
        
        
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
    
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    
        
          <%= form_for @contact do |f| %>
                <div class="col-md-6">    
                    <div class="well">
                        <div class="form-group">
                            
                          <h3>Personal Information</h3>
                          <%= f.label :name %>
                          <%= f.text_field :name, class: 'form-control' %>
                        
                          <%= f.label :email %>
                          <%= f.text_field :email, class: 'form-control' %>
                       
                          
                         
                          <%= f.label :Current_Address %>
                          <%= f.text_field :Current_Address, class: 'form-control' %>
                         
                          <%= f.label :city %>
                          <%= f.text_field :city, class: 'form-control' %>
                         
                          <%= f.label :state %>
                          <%= f.text_field :state, class: 'form-control' %>
                         
                          <%= f.label :zip %>
                          <%= f.text_field :zip, class: 'form-control' %>
                          
                       </div>  
                  </div>
              </div>
              <div class="col-md-6">
                <div class="well"> 
                      <div class="form-group"> 
                         
                         <%= f.label :dependents %>
                         <%= f.text_field :dependents, class: 'form-control' %>
                         
                         <%= f.label :how_long? %>
                         <%= f.text_field :how_long?, class: 'form-control' %>
                      
                         <%= f.label :home_phone_number  %>
                         <%= f.text_field :home_phone_number, class: 'form-control'  %>
                         
                         <%= f.label :Cell_number  %>
                         <%= f.text_field :Cell_number, class: 'form-control'  %>
                     
                         <%= f.label :rent_payment  %>
                         <%= f.text_field :rent_payment, class: 'form-control'  %>
                         
                         <%= f.label :Landlord  %>
                         <%= f.text_field :Landlord, class: 'form-control'  %>
                         
                         <%= f.label :phone_number  %>
                         <%= f.text_field :phone_number, class: 'form-control'  %>
                         
                         <%= f.label :name_on_lease?  %>
                         <%= f.text_field :name_on_lease?, class: 'form-control'  %>
                    </div>  
                </div>
             </div>
        
    <div class="row">
        <div class="col-md-6"> 
            <div class="well">
                <div class="form-group"> 
                    <h3>Employment Information</h3>
                     <%= f.label :employer  %>
                     <%= f.text_field :employer, class: 'form-control'  %>
                     
                     <%= f.label :occupation  %>
                     <%= f.text_field :occupation, class: 'form-control'  %>
                     
                     <%= f.label :how_long? %>
                     <%= f.text_field :how_long?, class: 'form-control' %>
                     
                     <%= f.label :supervisor  %>
                     <%= f.text_field :supervisor, class: 'form-control'  %>
                     
                     <%= f.label :phone_number  %>
                     <%= f.text_field :phone_number, class: 'form-control'  %>
                     
                     <%= f.label :monthly_income  %>
                     <%= f.text_field :monthly_income, class: 'form-control'  %>
                     
                </div>
                <%= f.submit 'Submit', class: 'btn btn-default' %>
            </div>
          <%end%>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Great America Sales and Rent to Own</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
  
</head>
<body>
  
<nav class = "navbar navbar-inverse navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class ="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
      <i class="fa fa-users navbar-brand"></i>
        GA
      <%end%>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class = "nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
        <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "About Us", about_path %> </li>
        <li> <%= link_to "Apply Now", new_contact_path %> </li>
        <li> <%= link_to "Contact Us", call_path %> </li>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <%end%>
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h2>About us</h2>

app/views/pages/appliances.html.erb
<DOCTYPE! html>
<head>
    
</head>
<body>
    <div class="jumbotron">
        <div class="container text-center">
            <h1>Appliances</h1>
        </div>
    </div>
    <div class="container">
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set </h2>
          <p><font color="white"></p>Queen bed/dressor/mirror/Nightstand 
          Cash Price:  $299.95* 
          Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     

    
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     
     
     
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
</div>
    
</body>





</html>
    

app/views/pages/apply.html.erb
<DOCTYPE! html>
<head>
    
    
    
    
</head>
<body>
    
    <div class="jumbotron">
        <div class="container text-center">
            <h1>Apply Now</h1>
        </div>
    </div>
   
    
    
    
    
    
    
</body>


</html>

app/views/pages/beds.html.erb
<DOCTYPE! html>
<head>
</head>
<body>
    <div class="jumbotron">
        <div class="container">
            <h1>Bedroom</h1>
        </div>
    </div>
    
    <div class="container">
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set </h2>
          <p><font color="white"></p>Queen bed/dressor/mirror/Nightstand 
          Cash Price:  $299.95* 
          Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     

    
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     
     
     
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
</div>
     
</body>



</html>

app/views/pages/call.html.erb
<DOCTYPE! html>
<head>
<body>
    
    <div class="jumbotron">
        <div class="container">
            <h1>Contact Us</h1>
        </div>
    
    
    
</body>
</head>

</html>

app/views/pages/contact.html.erb
<DOCTYPE! html>
<head>
<body>
    
    <div class="jumbotron">
        <div class="container">
            <h1>Contact Us</h1>
        </div>
    
    
    
</body>
</head>

</html>

app/views/pages/electronics.html.erb
<DOCTYPE! html>
<head>
<body>
    
    <div class="jumbotron">
        <div class="container">
            <h1>Electronics</h1>
        </div>
    
    </div>    
        <div class="container">
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set </h2>
          <p><font color="white"></p>Queen bed/dressor/mirror/Nightstand 
          Cash Price:  $299.95* 
          Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     

    
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     
     
     
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
</div>
    
    
</body>
</head>

</html>

app/views/pages/livingroom.html.erb
<DOCTYPE! html>
<head>
<body>
    
    <div class="jumbotron">
        <div class="container">
            <h1>Living Room</h1>
        </div>
    </div>
<div class="container">
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set </h2>
          <p><font color="white"></p>Queen bed/dressor/mirror/Nightstand 
          Cash Price:  $299.95* 
          Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     

    
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
     
     
     
    <div class="row">
      <div class="col-md-8">
          <img src="http://lcdn.1stopbedrooms.com/media/catalog/product/cache/1/image/cc0ec2d91bc4dd8becc1b9167d5c2be1/8/0/8064uset.jpg">    
      </div>
      <div class="col-md-4">
          <h2> <font color="white">Ashley B138 bedroom set</font></h2>
          <p><font color="white">Queen bed/dressor/mirror/Nightstand</font></p>
          <p><font color="white">Cash Price:  $299.95*</font></p>
          <p><font color="white">Call our store or <%= link_to "Apply Now", apply_path %> for payment options</font></p>
      </div>
     </div>
</div>
    
    
</body>
</head>

</html>